name: Run JUnit Tests
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'


      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.6.3

      - name: Cache dependencies
        run: mvn dependency:go-offline

      - name: Run JUnit Tests
        run: mvn test
